version: "2"
volumes:
  mongodbdata:
    external: true
  # jsondata:
  #   external: true
  # images:
  #   external: true
networks:
  kong-net:
    external: true
services:
  imclogin:
    container_name: imcloginc
    image: yknam/imclogin
    environment:
      - MONGO_URI=mongodb://imcmongo:27017/local
    restart: always
    build: .
    volumes:
      # //- jsondata:/data/json
      # - images:/data/images
      - /.env:/app/.env
    ports:
      - "9009:9009"
    links:
      - imcmongo
  imcmongo:
    container_name: imcmongoc
    image: yknam/imcmongo:first
    restart: always
    volumes:
      #- ../Program\ Files/MongoDB/Server/4.0/data:/data/db
      - mongodbdata:/data/db
    ports:
      - "9007:27017"
