version: "2"
# volumes:
#   mongodbdata:
#     external: true
#   # jsondata:
#   #   external: true
#   # images:
#   #   external: true
# networks:
#   kong-net:
#     external: true

services:
  imctemplate:
    container_name: imctemplatec
    image: yknam/imctemplate
    environment:
      - MONGO_URI=mongodb://imcmongo:27017/test
    restart: always
    build: .
    volumes:
      # //- jsondata:/data/json
      # - images:/data/images
      - /.env:/app/.env
    ports:
      - "9010:9010"
    # networks:
    #   - kong-net
    external_links:
      - imcmongo

  # imcmongo:
  #   container_name: imcmongoc
  #   image: yknam/imcmongo:first
  #   restart: always
  #   volumes:
  #     #- ../Program\ Files/MongoDB/Server/4.0/data:/data/db
  #     - mongodbdata:/data/db
  #   ports:
  #     - "9007:27017"
