name: Node Template Docker Build & Run

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
    
    # steps:
    # - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker-compose up

    # steps:
    #   - name: Check Out Repo
    #     uses: actions/checkout@v2

    #   - name: JSDoc run
    #     uses: npm run jsdoc

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    #   - name: Set up Docker Buildx
    #     id: buildx
    #     uses: docker/setup-buildx-action@v1

    #   - name: Build and push
    #     id: docker_build
    #     uses: docker/build-push-action@v2
    #     with:
    #       context: ./
    #       file: ./Dockerfile
    #       push: true
    #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodetemplate:latest

    #   - name: Image digest
    #     run: echo ${{ steps.docker_build.outputs.digest }}
